version: '3'

services:
  selfoss:
    container_name: selfoss
    image: hardware/selfoss
    volumes:
      - selfoss_data:/selfoss/data
    networks:
      - srv
    restart: unless-stopped
    expose:
      - 8888
    ports:
      - 127.0.0.1:8806:8888   

volumes: 
  selfoss_data:      