version: '3'

services:
  dokuwiki:
    image: linuxserver/dokuwiki
    container_name: dokuwiki
    restart: unless-stopped
    environment:
      - TZ=${TZ}
      - APP_URL=/ #optional      
    volumes:
      - ${ROOT_INSTALL}/data/dokuwiki:/config
    networks:
      - srv    
    expose:
      - 80
    ports:
      - 127.0.0.1:8805:80
