version: '3'

services:
  www:
    container_name: www
    image: kianby/www-madyanne
    restart: unless-stopped
    networks:
      - srv
    expose:
      - 80
    ports:
      - 127.0.0.1:8800:80
