version: '3'

services:
  deluge:
    container_name: deluge
    image: linuxserver/deluge
    restart: unless-stopped
    networks:
      - srv
    environment:
      DELUGE_LOGLEVEL: info
      TZ: ${TZ}    
    expose:
      - 8112
    ports:
      - ${DELUGE_TORRENT_PORT}:${DELUGE_TORRENT_PORT}/tcp
      - ${DELUGE_TORRENT_PORT}:${DELUGE_TORRENT_PORT}/udp
      - 127.0.0.1:8808:8112
    volumes:
      - deluge_config:/config:rw
      - deluge_downloads:/downloads:rw             

  torrent:
    container_name: torrent
    image: kianby/nginx-streaming
    restart: unless-stopped
    networks:
      - srv
    volumes:
      - deluge_downloads:/downloads:ro
    expose:
      - 80        
    # shortcut to bypass traefik limitation
    ports:
      - ${DOWNLOAD_HTTP_PORT}:80
           
    
volumes:
  deluge_config:
  deluge_downloads: