version: '3'

services:
  portainer:
    container_name: portainer
    image: portainer/portainer-ce
    command: -H unix:///var/run/docker.sock
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    networks:
      - srv
    restart: unless-stopped
    expose:
      - 9000    
    ports:
      - 127.0.0.1:8802:9000  

volumes:
  portainer_data:
